### PR TITLE
Adjusting Font size of the elements Issue #52

### LINKED ISSUE #52: [Bug]: Adjusting Font size of the elements in Footer section.
### Give a brief about the bug ✍️

In the Footer Section, the font size of the "PRIVACY NOTICE|TERMS OF SERVICE |[COOKIES INFO]|[CHROME GAMING]" are large and not correctly assigned horizontally.

### What is the expected behavior? 🤔

I would like to decrease the font size and also to align them such that there is a equal space between the vertical slashes and text.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by saiumasankar**
## PR Description 📜

In the Footer Section, the font size of the "PRIVACY NOTICE|TERMS OF SERVICE |[COOKIES INFO]|[CHROME GAMING]" are large and not correctly aligned horizontally. I contribute in this issue by following way:
- I used the flex concept in CSS to align the elements correctly in horizontal manner with equal spaces between them.
- I also took care of font size and hovering effects of the elements in footer.
- I didn't disturb any other code.
Fixes #52 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

correction

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by saiumasankar** [comment]
please assign level tag to the issue #52

**Comment by saiumasankar** [comment]
Please neglect the settings.json commit. It is created due to using of live server in VS code.

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Try to make it responsive

**Comment by saiumasankar** [comment]
As per the changes requested, I updated the styless.css file and made changes to make the elements of bottomline of the footer to be responsive. Please review it.

**Comment by Durgesh4993** [comment]
@saiumasankar Add a demo video

**Pull request closed without merging**
