### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DevanshPaliwal**
Updated the readme file and fixed some spelling mistakes and punctuations

## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <your_issue_number>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@DevanshPaliwal Add issue number

**Comment by DevanshPaliwal** [comment]
> @DevanshPaliwal Add issue number

Issue #83 
Please label it under Gssoc and assign a level.

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add our social media links in readme with icon

**Comment by DevanshPaliwal** [comment]
> Add our social media links in readme with icon

Can you please give me your instagram id or any other social media you have except linkedin?

**Review by DevanshPaliwal — COMMENTED** [review]
Added socials

**Comment by DevanshPaliwal** [comment]
Done

**Comment by DevanshPaliwal** [comment]
Please merge this @Durgesh4993 , i have added the socials

**Comment by DevanshPaliwal** [comment]
@Durgesh4993  i have added the changes as requested, please merge this PR

**Pull request closed without merging**
