### PR TITLE
Added cross button in color gradient platte

### PR DESCRIPTION
**Pull request by DevanshPaliwal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below - 

Fixes issue #84 , added cross button in gradient palette, even if both colors are selected and we press this cross button, those colors will not be changed. There is the apply gradient button for that. This cross button correctly closes the gradient palette without any problem.

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot is added in comments

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by DevanshPaliwal** [comment]
Screenshot 2024-06-18 003533

**Comment by DevanshPaliwal** [comment]
Here is the screenshot for the feature and proper working/testing has been performed by me before submitting PR.
Please label it under Gssoc and assign a level and merge into main branch @Durgesh4993

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Comment by DevanshPaliwal** [comment]
@Durgesh4993 where should i add the demo video?

**Comment by Durgesh4993** [comment]
Yes

**Comment by DevanshPaliwal** [comment]
@Durgesh4993 added changes.

**Comment by DevanshPaliwal** [comment]
@Durgesh4993 please merge this PR under Gssoc24

**Comment by DevanshPaliwal** [comment]
@Durgesh4993

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
